version: '3'

services:
  app:
    build: .
    ports:
      - '8080:8080'
    env_file:
      - .env
    depends_on:
      - db
    environment:
      SPRING_DATASOURSE_URL: 'jdbc:postgresql://db:5432/db'


  db:
    image: postgres:15.1-alpine
    container_name: postgres
    ports:
      - '5432:5432'
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
